- id: '1640719454463'
  alias: Cast dash to Study Display
  use_blueprint:
    path: kind3r/cast-and-re-cast-a-lovelace-view-to-a-google-hub.yaml
    input:
      dashboard: lovelace-displays
      player: media_player.study_display
      view: study
- id: '1640723847855'
  alias: Cast dash to Kitchen Display
  use_blueprint:
    path: kind3r/cast-and-re-cast-a-lovelace-view-to-a-google-hub.yaml
    input:
      dashboard: lovelace-displays
      player: media_player.kitchen_display
      view: kitchen