- id: '1640723847855'
  alias: Cast dash to Kitchen Display
  use_blueprint:
    path: kind3r/cast-and-re-cast-a-lovelace-view-to-a-google-hub.yaml
    input:
      dashboard: lovelace-displays
      player: media_player.kitchen_display
      view: kitchen
- id: '1653351407013'
  alias: 'Shed: Tag scanned'
  description: ''
  trigger:
  - platform: tag
    tag_id: c1df0752-06ad-4c20-b7c7-4a27514fef20
  - platform: tag
    tag_id: 5447b880-081d-4148-bd66-a3dc6ade6d7a
  - platform: tag
    tag_id: f518ea8a-3d21-4469-9810-73ef2eb50406
  condition: []
  action:
  - service: cover.toggle
    data: {}
    target:
      entity_id: cover.shed_door
  mode: restart
- id: '1654991000565'
  alias: 'Garage: Tag Toggle '
  description: ''
  trigger:
  - platform: tag
    tag_id: 897479f8-e0c2-4a5f-baff-3bc9d12ebea8
  - platform: tag
    tag_id: 9841fc8c-7717-4333-9d98-ec96110081a9
  condition: []
  action:
  - service: cover.toggle
    data: {}
    target:
      entity_id: cover.garage_door
  mode: restart
- id: '1658850559342'
  alias: 'Nursery: Mal''s Light to yellow in the morning'
  description: ''
  trigger:
  - platform: time
    at: 06:30:00
  condition: []
  action:
  - service: light.turn_on
    data:
      transition: 300
      color_name: yellow
      brightness: 3
    target:
      entity_id: light.mals_night_light
  mode: single
- id: '1659457903664'
  alias: 'Webhook: Turn on streaming light'
  description: ''
  trigger:
  - platform: webhook
    webhook_id: webhook-turn-on-streaming-light-4kRiS9jGUFwxiYOglCzBQyWx
  condition: []
  action:
  - service: light.turn_on
    data: {}
    target:
      entity_id: light.streaming_light
  - service: light.turn_off
    data: {}
    target:
      entity_id: light.study_lamp
  mode: single
- id: '1659472035994'
  alias: 'Webhook: Turn off streaming light'
  description: ''
  trigger:
  - platform: webhook
    webhook_id: webhook-turn-off-streaming-light-GeOQhu9SRKUfCpBzVnOoe0r0
  condition: []
  action:
  - service: light.turn_off
    data: {}
    target:
      entity_id: light.streaming_light
  - service: light.turn_on
    data: {}
    target:
      entity_id: light.study_lamp
  mode: single
- id: '1659884373089'
  alias: 'Walkway: Open door on tag'
  description: ''
  trigger:
  - platform: tag
    tag_id: fc38b85e-c2d2-40d2-8038-cd0c1a8f4707
  condition: []
  action:
  - service: lock.unlock
    data: {}
    target:
      entity_id: lock.entrance_lock
  mode: single
- id: '1659884469367'
  alias: 'Deck: Unlock door on tag '
  description: ''
  trigger:
  - platform: tag
    tag_id: 599d7fd2-3c51-4aea-a3e3-556fb48a22e6
  condition: []
  action:
  - service: lock.unlock
    data: {}
    target:
      entity_id: lock.deck_door_lock
  mode: single
- id: '1660078930986'
  alias: 'Nursery: Mal''s night to red at night'
  description: ''
  trigger:
  - platform: time
    at: '18:00:00'
  condition: []
  action:
  - service: light.turn_on
    data:
      color_name: red
      brightness: 3
    target:
      entity_id: light.mals_night_light
  mode: single
- id: '1660784236531'
  alias: 'Closet: Wal switch light toggle'
  description: ''
  trigger:
  - platform: event
    event_type: zwave_js_value_notification
    event_data:
      domain: zwave_js
      node_id: 28
      endpoint: 0
      device_id: 91e941c1783ff55e23ce6b2aafbdb35e
      command_class: 91
      command_class_name: Central Scene
      label: Scene 001
      property: scene
      property_name: scene
      property_key: '001'
      property_key_name: '001'
  condition: []
  action:
  - service: light.toggle
    data: {}
    target:
      entity_id: light.closet_light
  mode: single
- id: '1661883340983'
  alias: 'Closet: Button'
  description: ''
  use_blueprint:
    path: mcflexus/zha-ikea-tradfri-shortcut-button.yaml
    input:
      shortcut_button: b08b8001288481889aab20273ea044c6
      button_short:
      - service: light.toggle
        data: {}
        target:
          entity_id: light.closet_light
      button_long:
      - service: script.white_noise_baby_speaker
        data: {}
- id: house_climate_on_presence
  alias: 'Hallway: Set climate on/off based on presence'
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.home_empty
  - platform: state
    entity_id: sensor.home_state
  - platform: homeassistant
    event: start
  - platform: state
    entity_id:
    - binary_sensor.deck_door_open
    - binary_sensor.entrance_door_open
    to:
    - 'on'
    - 'off'
    for: 00:02:00
  - platform: state
    entity_id: climate.hallway
    for: 00:01:00
  action:
  - choose:
    - conditions:
      - '{{ is_state(''binary_sensor.home_empty'', ''off'') }}'
      - '{{ is_state(''binary_sensor.deck_door_open'', ''off'') }}'
      - '{{ is_state(''binary_sensor.entrance_door_open'', ''off'') }}'
      sequence:
      - service: climate.set_temperature
        data:
          temperature: '{{ states(''input_number.climate_temperature'') | float }}'
          hvac_mode: '{{ states(''input_select.climate_mode'') | string }}'
        target:
          entity_id: climate.hallway
    default:
    - service: climate.set_hvac_mode
      data:
        hvac_mode: 'off'
      target:
        entity_id: climate.hallway
  mode: restart
- id: '1663713505830'
  alias: 'Study: Occupancy'
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.study_occupancy
  condition:
  - condition: state
    entity_id: input_boolean.study_guest_present
    state: 'off'
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: binary_sensor.study_occupancy
        state: 'on'
      sequence:
      - service: number.set_value
        data:
          value: '7200'
        target:
          entity_id: number.study_dash_screensaver_timer
      - service: switch.turn_off
        data: {}
        target:
          entity_id: switch.study_dash_screensaver
      - service: light.turn_on
        data: {}
        target:
          entity_id:
          - light.study_ceiling_lights
          - light.study_lamp
          - light.streaming_light
    default:
    - service: switch.turn_on
      data: {}
      target:
        entity_id: switch.study_dash_screensaver
    - service: light.turn_off
      data: {}
      target:
        entity_id:
        - light.study_ceiling_lights
        - light.study_lamp
        - light.streaming_light
    - service: number.set_value
      data:
        value: '1'
      target:
        entity_id: number.study_dash_screensaver_timer
  mode: single
- id: study_ac_off_when_inactive
  alias: 'Study: AC off when inactive'
  trigger:
    platform: state
    entity_id: binary_sensor.study_occupancy
    to: 'off'
  action:
  - service: climate.turn_off
    entity_id: climate.study_ac
- id: study_blinds_shut
  alias: 'Study: Blinds shut at sunset'
  trigger:
  - platform: sun
    event: sunset
  action:
  - service: cover.close_cover
    target:
      entity_id: cover.study_blind
- id: study_blinds_open
  alias: 'Study: Blinds open in the morning'
  trigger:
  - platform: time
    at: 08:00
  action:
  - service: cover.open_cover
    target:
      entity_id: cover.study_blind
- id: '1644372711313'
  alias: 'Study: Double Tap Switch'
  use_blueprint:
    path: kpine/ge_double.yaml
    input:
      device: 771312246077ff9c4bb264b87f9778f7
      double_tap_on:
      - scene: scene.study_lights_on_day
      double_tap_off:
      - scene: scene.study_lights_off
- id: '1663779432861'
  alias: 'Study: Blind Open/Close'
  description: ''
  use_blueprint:
    path: S-Collison/ikea_open_close_remote.yaml
    input:
      remote: 96acb7fe9be494fddeeba65997db51a1
      cover:
        entity_id: cover.study_blind
- id: '1663779488762'
  alias: 'Nursery: Blind Open/Close'
  description: ''
  use_blueprint:
    path: S-Collison/ikea_open_close_remote.yaml
    input:
      remote: 8252a3a532e64de7f650e0209a8d6dc3
      cover:
        entity_id: cover.nursery_blind
- id: '1663779650573'
  alias: 'Bedroom: Blinds Open/Close'
  description: ''
  use_blueprint:
    path: S-Collison/ikea_open_close_remote.yaml
    input:
      remote: 5227e002c9b20a4248fdd6f793186735
      cover:
        entity_id:
        - cover.bedroom_blind_left
        - cover.bedroom_blind_center_window_covering
        - cover.bedroom_blind_right
- id: someone_is_coming_home
  alias: 'Home: Someone is coming home'
  trigger:
    platform: zone
    entity_id:
    - person.ox
    - person.sue
    - person.callie
    zone: zone.home
    event: enter
  action:
  - service: switch.turn_on
    entity_id: switch.garage_lights
  - service: lock.unlock
    target:
      entity_id:
      - lock.deck_door_lock
      - lock.entrance_lock
- id: house_locks
  alias: 'Living Room: Set locks to correct state'
  trigger:
  - platform: state
    entity_id: binary_sensor.home_empty
  - platform: state
    entity_id: sensor.home_state
  - platform: homeassistant
    event: start
  - platform: state
    entity_id:
    - lock.deck_door_lock
    from: locked
    to: unlocked
    for: 00:15:00
  action:
  - choose:
    - alias: Lock house
      conditions:
      - condition: or
        conditions:
        - '{{ is_state(''binary_sensor.home_empty'', ''on'') }}'
        - '{{ is_state(''sensor.home_state'', ''night'') }}'
      sequence:
      - service: lock.lock
        target:
          entity_id:
          - lock.deck_door_lock
          - lock.entrance_lock
        data: {}
    default:
    - service: lock.unlock
      target:
        entity_id:
        - lock.deck_door_lock
        - lock.entrance_lock
      data: {}
- id: '1665792421763'
  alias: 'Nursery: Scene TL: Toggle Blinds'
  description: Double tap toggle blinds
  trigger:
  - platform: event
    event_type: zwave_js_value_notification
    event_data:
      domain: zwave_js
      device_id: 15d84c77fe7d0af006dbf319e0c281e5
      command_class_name: Central Scene
      label: Scene 001
      value: KeyPressed2x
  condition: []
  action:
  - service: light.turn_on
    data:
      brightness_pct: 81
    target:
      entity_id: light.nursery_light
  mode: single
- id: '1665792534882'
  alias: 'Nursery: Scene TR: Day Mode'
  description: Set day mode
  trigger:
  - platform: event
    event_type: zwave_js_value_notification
    event_data:
      domain: zwave_js
      device_id: 15d84c77fe7d0af006dbf319e0c281e5
      command_class_name: Central Scene
      label: Scene 002
      value: KeyPressed2x
  condition: []
  action:
  - service: cover.open_cover
    data: {}
    target:
      entity_id: cover.nursery_blind
  - service: light.turn_on
    data:
      color_name: yellow
      brightness: 1
    target:
      entity_id: light.mals_night_light
  - service: light.turn_on
    data:
      brightness: 192
    target:
      entity_id:
      - light.nursery_ceiling
      - light.nursery_light
  - service: climate.set_hvac_mode
    data:
      hvac_mode: cool
    target:
      entity_id: climate.dyson_heater
  mode: single
- id: '1665792617206'
  alias: 'Nursery: Scene BR: Night mode'
  description: Turn on night mode for wall scene controller
  trigger:
  - platform: event
    event_type: zwave_js_value_notification
    event_data:
      domain: zwave_js
      device_id: 15d84c77fe7d0af006dbf319e0c281e5
      command_class_name: Central Scene
      label: Scene 004
      value: KeyPressed2x
  condition: []
  action:
  - service: script.nursery_lights_out_speaker_on
    data: {}
  - service: cover.close_cover
    data: {}
    target:
      entity_id: cover.nursery_blind
  mode: single
- id: '1665849187744'
  alias: 'Nursery: Scene Center: Lights off'
  description: Turn off lights
  trigger:
  - platform: event
    event_type: zwave_js_value_notification
    event_data:
      domain: zwave_js
      device_id: 15d84c77fe7d0af006dbf319e0c281e5
      command_class_name: Central Scene
      label: Scene 005
      value: KeyPressed2x
  condition: []
  action:
  - service: light.turn_off
    data: {}
    target:
      entity_id:
      - light.nursery_light
      - light.nursery_ceiling
      - light.mals_night_light
  mode: single
- id: '1669485973281'
  alias: 'Driveway: Lights on at night'
  description: ''
  trigger:
  - platform: homeassistant
    event: start
  - platform: sun
    event: sunset
    offset: 0
  - platform: state
    entity_id:
    - sensor.home_state
  condition: []
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: sensor.home_state
        state: evening
      sequence:
      - service: light.turn_on
        data: {}
        target:
          entity_id: light.outside_lights
    default:
    - service: light.turn_off
      data: {}
      target:
        entity_id: light.outside_lights
  mode: single
