blueprint:
  name: IKEA Open/Close Remote
  description: '''Control your roller blind with an IKEA 2 button remote (the square
    ones).

    this is the remote that''s been delivered by the "Fytur" and " Kadrilj"

    roller blinds.''

    '
  domain: automation
  input:
    remote:
      name: Remote
      description: IKEA remote to use
      selector:
        device:
          integration: zha
          model: TRADFRI open/close remote
          multiple: false
    cover:
      name: Roller Blind
      description: Roller blinds to control
      selector:
        target:
          entity:
            domain: cover
  source_url: https://gist.github.com/S-Collison/3f7da1cfb6070ba0c5641dd5c4f2d54d
mode: single
max_exceeded: silent
trigger:
- platform: event
  event_type: zha_event
  event_data:
    device_id: !input remote
action:
- variables:
    command: '{{ trigger.event.data.command }}'
- choose:
  - conditions:
    - '{{ command == ''up_open'' }}'
    sequence:
    - service: cover.open_cover
      target: !input cover
  - conditions:
    - '{{ command == ''down_close'' }}'
    sequence:
    - service: cover.close_cover
      target: !input cover
