---
automation:
  - id: front_door_light_at_night
    alias: "Living Room: Walking around lights at night"
    mode: restart
    max_exceeded: silent
    condition: "{{ is_state('sensor.home_state', 'night') }}"
    trigger:
      platform: state
      entity_id:
        - binary_sensor.hallway_sensor_motion
        - binary_sensor.landing_sensor_motion
      from: "off"
      to: "on"
    action:
      - service: light.turn_on
        data:
          entity_id: light.front_door_light
          brightness: 60
          transition: 3
      - wait_for_trigger:
          platform: state
          entity_id:
            - binary_sensor.hallway_sensor_motion
            - binary_sensor.landing_sensor_motion
          from: "on"
          to: "off"
      - delay: 00:05:00
      - service: light.turn_off
        data:
          entity_id: light.front_door_light
          transition: 3

  - id: front_door_light_off_at_sunrise
    alias: "Living Room: Turn off front door light at sunrise"
    trigger:
      platform: sun
      event: sunrise
      offset: "+01:00:00"
    action:
      service: light.turn_off
      entity_id: light.front_door_light

  - id: front_door_dash_set_screensaver_timeout
    alias: "Living Room: Front Door Dash - Set Screensaver Timeout"
    trigger:
      - platform: state
        entity_id: sensor.home_state
      - platform: homeassistant
        event: start
    action:
      - service: number.set_value
        entity_id: number.front_door_dash_screensaver_timer
        data:
          value: >
            {% if is_state('sensor.home_state', 'day') %}
              1800
            {% elif is_state('sensor.home_state', 'evening') %}
              60
            {% else %}
              10
            {% endif %}
      - service: button.press
        entity_id: button.front_door_dash_load_start_url
      - service: light.turn_on
        target:
          entity_id: light.front_door_dash_screen
        data:
          brightness: 40

  - id: kitchen_speaker_announce_trash_day
    alias: "Living Room: Kitchen Speaker - Announce Trash Dash"
    trigger:
      - platform: time
        at: "07:45:00"
    condition:
      condition: or
      conditions:
        - condition: state
          entity_id: sensor.garbage_trash
          state: "0"
        - condition: state
          entity_id: sensor.garbage_recycling
          state: "0"
    action:
      - service: media_player.volume_set
        data:
          entity_id: media_player.kitchen_display
          volume_level: 0.8
      - delay:
          seconds: 2
      - service: tts.cloud_say
        data:
          entity_id: media_player.kitchen_display
          message: >
            It is Garbage day.  Don't forget to take out the trash
            {% if is_state('sensor.garbage_recycling', '0') %}
             and the recycling
            {% endif %}
      - delay:
          seconds: 10
      - service: media_player.volume_set
        data:
          entity_id: media_player.kitchen_display
          volume_level: 0.4
