---
input_boolean:
  study_guest_present:
    name: "Study: Guest is present"
    initial: off
    icon: mdi:desk

template:
  - binary_sensor:
      - name: study_active
        state: >
          {{ is_state('binary_sensor.study_door_open', 'on') 
            or is_state('binary_sensor.study_sensor_motion', 'on') }}
        delay_off: 00:05:00

scene:
  - id: study_lights_on_day
    name: "Study: Lights on day"
    entities:
      switch.study_ceiling_lights: "on"
      light.study_lamp:
        state: "on"
        brightness: 255
        color_temp: 250 # cool-ish white

  - id: study_lights_on_night
    name: "Study: Lights on night"
    entities:
      switch.study_ceiling_lights: "off"
      light.study_lamp:
        state: "on"
        brightness: 255
        color_temp: 420 # warm-ish white

  - id: study_lights_off
    name: "Study: Lights off"
    entities:
      switch.study_ceiling_lights: "off"
      light.study_lamp:
        state: "off"

automation:
  - id: study_active
    alias: "Study: Lights on when active"
    mode: restart
    variables:
      active_scene: >
        {% if is_state('sensor.home_state', 'day') %}
        scene.study_lights_on_day
        {% else %}
        scene.study_lights_on_night
        {% endif %}
    trigger:
      platform: state
      entity_id: binary_sensor.study_active
      from: "off"
      to: "on"
    condition: "{{ is_state('input_boolean.study_guest_present', 'off') }}"
    action:
      - service: scene.turn_on
        target:
          entity_id: "{{ active_scene }}"
        data:
          transition: 10
      - wait_for_trigger:
          platform: state
          entity_id: binary_sensor.study_active
          from: "on"
          to: "off"
      - delay: "01:00:00"
      - service: scene.turn_on
        target:
          entity_id: scene.study_lights_off
        data:
          transition: 10

  - id: study_blinds_shut
    alias: "Study: Blinds shut at sunset"
    trigger:
      - platform: sun
        event: sunset
    action:
      - service: cover.close_cover
        target:
          entity_id: cover.study_blind

  - id: study_blinds_open
    alias: "Study: Blinds open at 9am"
    trigger:
      - platform: time
        at: 09:00
    action:
      - service: cover.open_cover
        target:
          entity_id: cover.study_blind

  - id: study_blind_remote_open
    alias: "Study: Blind Remote - Open"
    trigger:
      - device_id: 96acb7fe9be494fddeeba65997db51a1
        domain: zha
        platform: device
        type: remote_button_short_press
        subtype: open
    action:
      - service: cover.open_cover
        target:
          entity_id: cover.study_blind

  - id: study_blind_remote_close
    alias: "Study: Blind Remote - Close"
    trigger:
      - device_id: 96acb7fe9be494fddeeba65997db51a1
        domain: zha
        platform: device
        type: remote_button_short_press
        subtype: close
    action:
      - service: cover.close_cover
        target:
          entity_id: cover.study_blind

  - id: "1644372711313"
    alias: "Study: Double Tap Switch"
    use_blueprint:
      path: kpine/ge_double.yaml
      input:
        # switch.study_lights
        device: 771312246077ff9c4bb264b87f9778f7
        double_tap_on:
          - scene: scene.study_lights_on_day
        double_tap_off:
          - scene: scene.study_lights_off
