---
automation:
  - id: "1649526423836"
    alias: "Walkway: Lights"
    description: Walkway and driveway lights on motion
    trigger:
      - platform: state
        entity_id: binary_sensor.walkway_sensor_motion
        to: "on"
      - platform: state
        entity_id: binary_sensor.walkway_sensor_motion
        to: "off"
        for: "00:05:00"
      - platform: state
        entity_id: sensor.home_state
      - platform: homeassistant
        event: start
    action:
      - choose:
          - conditions:
              - condition: state
                entity_id: binary_sensor.walkway_sensor_motion
                state: "on"
              - "{{ is_state('sun.sun', 'below_horizon') }}"
            sequence:
              - service: light.turn_on
                target:
                  entity_id:
                    - light.walkway_lights
                    - light.driveway_lights
          - conditions:
              - condition: or
                conditions:
                  - "{{ is_state('sun.sun', 'above_horizon') }}"
                  - condition: state
                    entity_id: binary_sensor.walkway_sensor_motion
                    state: "off"
            sequence:
              - service: light.turn_off
                target:
                  entity_id:
                    - light.walkway_lights
                    - light.driveway_lights
    mode: restart
