---
template:
  - binary_sensor:
      - name: walkway_active
        state: >
          {{ 
            is_state('binary_sensor.entrance_door_open', 'on')
            or is_state('binary_sensor.binary_sensor.walkway_sensor_motion', 'on') 
            or is_state('cover.garage_door', 'open') 
          }}
        delay_off: "00:05:00"

automation:
  - id: "1649526423836"
    alias: "Walkway: Lights"
    description: Walkway and driveway lights on motion
    trigger:
      - platform: state
        entity_id: binary_sensor.walkway_active
      - platform: state
        entity_id: sensor.home_state
      - platform: homeassistant
        event: start
    action:
      - choose:
          - conditions:  # implicit and
              - "{{ is_state('sun.sun', 'below_horizon') }}"
              - "{{ is_state('binary_sensor.walkway_active', 'on') }}"
            sequence:
              - service: light.turn_on
                target:
                  entity_id:
                    - light.walkway_lights
                    - light.driveway_lights
          - conditions:
              - condition: or
                conditions:
                  - "{{ is_state('sun.sun', 'above_horizon') }}"
                  - "{{ is_state('binary_sensor.walkway_active', 'off') }}"
            sequence:
              - service: light.turn_off
                target:
                  entity_id:
                    - light.walkway_lights
                    - light.driveway_lights
    mode: restart
